[build-system]
build-backend = "setuptools.build_meta"
requires = [ "setuptools>=77" ]

[project]
authors = [ { email = "contact@amaanq.com", name = "Amaan Qureshi" } ]
classifiers = [
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Compilers",
  "Topic :: Text Processing :: Linguistic",
  "Typing :: Typed",
]
description = "KDL grammar for tree-sitter"
keywords = [ "incremental", "parsing", "tree-sitter", "kdl" ]
license = "MIT"
name = "tree-sitter-kdl"
readme = "README.md"
requires-python = ">=3.10"
version = "1.1.0"

[project.urls]
Homepage = "https://github.com/amaanq/tree-sitter-kdl"

[project.optional-dependencies]
core = [ "tree-sitter~=0.25" ]

[tool.cibuildwheel]
build = "cp310-*"
build-frontend = "build"
