#!/usr/bin/env bash

set -eu

cd "$(dirname "$0")/.."

function clone_repo {
	owner=$1
	name=$2
	sha=$3

	path=examples/$name
	if [ ! -d "$path" ]; then
		echo "Cloning $owner/$name"
		git clone "https://github.com/$owner/$name" "$path"
	fi

	pushd "$path" >/dev/null
	actual_sha=$(git rev-parse HEAD)
	if [ "$actual_sha" != "$sha" ]; then
		echo "Updating $owner/$name to $sha"
		git fetch
		git reset --hard "$sha"
	fi
	popd >/dev/null
}

clone_repo kdl-org kdl 6feeccc491808fe0b5425a18aa7ab4a8ac435e55
clone_repo kdl-org kdl-rs 8c028e5ea189470f07c5c848ab778f3d63ba89ab
clone_repo kdl-org kdljs bb874a595e6f712950795ecaad62f24fd945f03d
clone_repo kdl-org kdl-php 390fdc5ab8e2749feb01a113e8feb028de0861b3

declare -A known_failures=()
while IFS= read -r file; do
	known_failures["$file"]=1
done < script/known_failures.txt

# Remove input directories
find examples -type d -name input -exec rm -rf {} +

mapfile -t example_files < <(find examples -name "*.kdl")
files_to_parse=()
for file in "${example_files[@]}"; do
	if [[ -z "${known_failures[$file]:-}" ]]; then
		files_to_parse+=("$file")
	fi
done

tree-sitter parse -q "${files_to_parse[@]}"

example_count=${#example_files[@]}
failure_count=${#known_failures[@]}
success_count=$((example_count - failure_count))
success_percent=$(bc -l <<<"100*${success_count}/${example_count}")

printf \
	"Successfully parsed %d of %d example files (%.1f%%)\n" \
	"$success_count" "$example_count" "$success_percent"
