name: CI

on:
  push:
    branches: [master]
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp
  pull_request:
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    name: Test parser
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-26]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@v2
        with:
          tree-sitter-ref: v0.27.0
      - name: Run tests
        uses: tree-sitter/parser-test-action@v3
        with:
          test-rust: true
      - name: Parse examples
        if: runner.os == 'Linux'
        run: script/parse-examples
